{{- if not .Values.appStorage.existingClaim }}
{{- if .Values.appStorage.claimName }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appStorage.claimName }}
  labels:
    {{- include "appstore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appStorage.storageSize }}
  storageClassName: {{ .Values.appStorage.storageClass }}
{{- end }}
{{- end }}
