{{- if .Values.appStorage.enabled }}
{{- if not .Values.appStorage.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.appStorage.claimName }}
  name: {{ .Values.appStorage.claimName }}
  {{- else }}
  name: appstore-logs-pvc
  {{- end }}
  labels:
    {{- include "appstore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appStorage.storageSize }}
  storageClassName: {{ .Values.appStorage.storageClass }}
{{- end }}
{{- end }}
