apiVersion: v1
kind: Secret
metadata:
  name: atlas-env
data:
  {{- if .Values.apps.DATASOURCE_PASSWORD }}
  DATASOURCE_PASSWORD: {{ .Values.apps.DATASOURCE_PASSWORD | b64enc }}
  {{- end }}
  {{- if .Values.apps.FLYWAY_DATASOURCE_PASSWORD }}
  FLYWAY_DATASOURCE_PASSWORD: {{ .Values.apps.FLYWAY_DATASOURCE_PASSWORD | b64enc }}
  {{- end }}
  {{- if .Values.apps.FLYWAY_DATASOURCE_CONNECTION_HOST }}
  FLYWAY_DATASOURCE_CONNECTION_HOST: {{ .Values.apps.FLYWAY_DATASOURCE_CONNECTION_HOST | b64enc }}
  {{- end }}  
  {{- if .Values.apps.DATASOURCE_CONNECTION_HOST }}
  DATASOURCE_CONNECTION_HOST: {{ .Values.apps.DATASOURCE_CONNECTION_HOST | b64enc }}
  {{- end }}
  {{- if .Values.apps.DATASOURCE_USERNAME }}
  DATASOURCE_USERNAME: {{ .Values.apps.DATASOURCE_USERNAME | b64enc }}
  {{- end }}
  {{- if .Values.apps.FLYWAY_DATASOURCE_USERNAME }}
  FLYWAY_DATASOURCE_USERNAME: {{ .Values.apps.FLYWAY_DATASOURCE_USERNAME | b64enc }}
  {{- end }}
