apiVersion: v1
kind: Secret
metadata:
  name: cloud-top-env
data:
  VNC_PW: {{ randAlphaNum 12 | b64enc | quote }}
  PUID: {{ .Values.apps.WEBTOP_PUID | b64enc | quote }}
  PGID: {{ .Values.apps.WEBTOP_PGID | b64enc | quote }}
