{{- if .Values.security.isolatedApps }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "appstore.fullname" . }}-default-deny-ingress
spec:
  podSelector:
    matchLabels:
      executor: tycho
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ambassador
{{- end }}
