apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-env
data:
  PGADMIN_DEFAULT_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}
  PGADMIN_DEFAULT_EMAIL: {{ .Values.apps.PGADMIN_EMAIL | b64enc | quote }}
  PGADMIN_CONFIG_SERVER_MODE: {{ "False" | b64enc | quote }}
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: {{ "False" | b64enc | quote }}
