{{- if not .Values.postgresql.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.oauth.claimName }}
  name: {{ .Values.oauth.claimName }}
  {{- else }}
  name: appstore-oauth-pvc
  {{- end }}
  labels:
    {{- include "appstore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  {{ if .Values.oauth.storageClass }}
  storageClassName: {{ .Values.oauth.storageClass }}
  {{- end }}
{{- end }}
