{{- if .Values.userStorage.createPVC }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.global.stdnfsPvc }}
  labels:
    {{- include "appstore.labels" . | nindent 4 }}
  {{- if .Values.userStorage.retain }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.userStorage.storageSize }}
  {{ if .Values.userStorage.storageClass }}
  storageClassName: {{ .Values.userStorage.storageClass }}
  {{- end }}
{{- end }}
