{{- if eq .Values.userStorage.createPVC true }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.global.stdnfsPvc }}
  labels:
    {{- include "appstore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.userStorage.storageSize }}
  {{ if .Values.userStorage.storageClass }}
  storageClassName: {{ .Values.userStorage.storageClass }}
  {{- end }}
{{- end }}
