{{- if .Values.webtop.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: webtop-octave-env
data:
  PUID: {{ .Values.apps.WEBTOP_PUID | b64enc | quote }}
  PGID: {{ .Values.apps.WEBTOP_PGID | b64enc | quote }}
{{- end }}